// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVFXXaNz31Hn5qb8cQIpGr2-5T1r2iCqw',
    appId: '1:495694008336:web:09068da0ad23873d143a95',
    messagingSenderId: '495694008336',
    projectId: 'fluttertp9',
    authDomain: 'fluttertp9.firebaseapp.com',
    storageBucket: 'fluttertp9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq0-N9ijJj2xVI2uPxaRybJLNwMpDsdGM',
    appId: '1:495694008336:android:21656debb13647f5143a95',
    messagingSenderId: '495694008336',
    projectId: 'fluttertp9',
    storageBucket: 'fluttertp9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFtdP2dhzJIGzBIGuOYT2DJi2uxznXpHA',
    appId: '1:495694008336:ios:dc84cfa86c671f5e143a95',
    messagingSenderId: '495694008336',
    projectId: 'fluttertp9',
    storageBucket: 'fluttertp9.appspot.com',
    iosBundleId: 'com.example.flutterToDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFtdP2dhzJIGzBIGuOYT2DJi2uxznXpHA',
    appId: '1:495694008336:ios:dc84cfa86c671f5e143a95',
    messagingSenderId: '495694008336',
    projectId: 'fluttertp9',
    storageBucket: 'fluttertp9.appspot.com',
    iosBundleId: 'com.example.flutterToDoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVFXXaNz31Hn5qb8cQIpGr2-5T1r2iCqw',
    appId: '1:495694008336:web:c151b253c91b7c82143a95',
    messagingSenderId: '495694008336',
    projectId: 'fluttertp9',
    authDomain: 'fluttertp9.firebaseapp.com',
    storageBucket: 'fluttertp9.appspot.com',
  );
}
